# Generated by Django 4.2.3 on 2023-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_Form_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='feeddback',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='log',
            name='passworld',
        ),
    ]
